# Generated by Django 6.1.1 on 2026-09-07 20:33

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chores", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Chore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("room", models.CharField(max_length=100)),
                (
                    "points",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("open", "Open"), ("claimed", "Claimed")],
                        default="open",
                        max_length=10,
                    ),
                ),
                (
                    "claimed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="claimed_chores",
                        to="chores.user",
                    ),
                ),
                (
                    "household",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chores",
                        to="chores.household",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WeeklyCompletion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "points_awarded",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("week_start_date", models.DateField()),
                (
                    "completed_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "chore",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="completions",
                        to="chores.chore",
                    ),
                ),
                (
                    "household",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="completions",
                        to="chores.household",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="completions",
                        to="chores.user",
                    ),
                ),
            ],
        ),
    ]
